language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx
  - windows

script:
  - cargo build --locked --verbose --all
  - cargo test --locked --verbose --all
